### PR TITLE
homePage

### PR DESCRIPTION
**Pull request by mikefgalvin**

### CODE REVIEW

**Comment by chazkiker2** [comment]
I updated my seed data; pictures should render correctly now (at least for the most part).

**Comment by mikefgalvin** [comment]
Images are now rendering correctly, thanks Chaz! Some images are missing but I don't think that matters with the randomized data. 

@reesharper I put in a search input and filter but both are non-functional until we can connect them correctly with the backend data.

**Comment by chazkiker2** [comment]
@mikefgalvin @Ironipad64  @reesharper slack servers are down!! what are y'all hoping to do?

**Comment by chazkiker2** [comment]
@Ironipad64 @reesharper chat thread going on this Trello card: https://trello.com/c/hscTjJ58

**Pull request merged**
